#ifndef TESTHEADER_H
#define TESTHEADER_H

#ifdef TEST_FIRST_FUNCTION
#include TOP_DOWN_ITERATIVE_TEST_FIRST
#endif //TEST_FIRST_FUNCTION

#ifdef TEST_FOLLOW_FUNCTION
#include TOP_DOWN_ITERATIVE_TEST_FOLLOW
#endif //TEST_FOLLOW_FUNCTION

#ifdef TEST_PARSE_TABLE_FUNCTION
#include TOP_DOWN_ITERATIVE_TEST_PARSETABLE
#endif //TEST_PARSE_TABLE_FUNCTION

#endif